// src/UIs/vuejs/src/components/Star.vue
<template>
  <div class="crop" :style="{width: starWidth + 'px'}" :title="rating" @click="onClick">
    <div style="width: 75px">
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
</template>
<script>
export default {
  props: ["rating"],
  data() {
    return {};
  },
  computed: {
    starWidth() {
      return (this.rating * 75) / 5;
    }
  },
  methods: {
    onClick() {
      this.$emit("ratingClicked", `The rating ${this.rating} was clicked!`);
    }
  }
};
</script>
<style scoped>
.crop {
  overflow: hidden;
}
div {
  cursor: pointer;
}
</style>

// src/UIs/reactjs/src/components/Star/Star.js
import React from "react";

import classes from "./Star.module.css";

const Star = props => {
  const width = (props.rating * 75) / 5;
  return (
    <div
      className={classes.Star}
      style={{ width: width }}
      title="rating"
      onClick={() =>
        props.ratingClicked
          ? props.ratingClicked(`The rating ${props.rating} was clicked!`)
          : null
      }
    >
      <div style={{ width: "75px" }}>
        <span className="fa fa-star"></span>
        <span className="fa fa-star"></span>
        <span className="fa fa-star"></span>
        <span className="fa fa-star"></span>
        <span className="fa fa-star"></span>
      </div>
    </div>
  );
};

export default Star;
