// src/UIs/bff/reactjs/src/components/FilePicker/FilePicker.tsx
import type { ChangeEventHandler } from "react";
import { FileUp } from "lucide-react";
import "./FilePicker.css";

type Props = {
  id: string;
  name: string;
  label: string;
  hint: string;
  file: File | null;
  invalid?: boolean;
  accept?: string;
  onChange: ChangeEventHandler<HTMLInputElement>;
};

const FilePicker = ({ id, name, label, hint, file, invalid = false, accept, onChange }: Props) => (
  <div>
    <label className={`file-picker${invalid ? " file-picker-invalid" : ""}`}>
      <input id={id} name={name} type="file" accept={accept} title={file?.name} aria-label={label} aria-describedby={`${id}-hint`} aria-invalid={invalid} onChange={onChange} />
      <span className="file-picker-icon"><FileUp size={22} aria-hidden="true" /></span>
      <span className="file-picker-copy">
        <strong className="file-picker-title">{file ? file.name : "Choose a file"}</strong>
        <span id={`${id}-hint`} className="file-picker-hint">{hint}</span>
      </span>
      <span className="file-picker-button">Browse</span>
    </label>
    {invalid && <div className="text-danger small mt-1">Select a file</div>}
  </div>
);

export default FilePicker;

// src/UIs/angular/src/app/shared/file-picker.component.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";
import { ActionIconComponent } from "./action-icon.component";

@Component({
  selector: "app-file-picker",
  standalone: true,
  imports: [ActionIconComponent],
  template: `
    <div>
      <label class="file-picker" [class.file-picker-invalid]="invalid">
        <input [id]="inputId" [name]="name" type="file" [accept]="accept" [title]="file?.name || ''" [attr.aria-label]="label" [attr.aria-describedby]="inputId + '-hint'" [attr.aria-invalid]="invalid" (change)="fileSelected($event)" />
        <span class="file-picker-icon"><app-action-icon action="import" /></span>
        <span class="file-picker-copy">
          <strong class="file-picker-title">{{ file ? file.name : 'Choose a file' }}</strong>
          <span class="file-picker-hint" [id]="inputId + '-hint'">{{ hint }}</span>
        </span>
        <span class="file-picker-button">Browse</span>
      </label>
      @if (invalid) { <div class="text-danger small mt-1">Select a file</div> }
    </div>
  `,
  styleUrls: ["./file-picker.component.css"],
})
export class FilePickerComponent {
  @Input() inputId = "";
  @Input() name = "";
  @Input() label = "File";
  @Input() hint = "Any file type";
  @Input() file: File | null = null;
  @Input() invalid = false;
  @Input() accept = "";
  @Output() fileChange = new EventEmitter<FileList | null>();

  fileSelected(event: Event) {
    this.fileChange.emit((event.target as HTMLInputElement).files);
  }
}
