// src/UIs/angular/src/app/shared/timer.component.ts
import { Component, OnInit, OnDestroy } from "@angular/core";

@Component({
  selector: "app-timer",
  templateUrl: "./timer.component.html",
  styleUrls: [],
})
export class TimerComponent implements OnInit, OnDestroy {
  interval: any;
  years: number;
  months: number;
  days: number;
  hours: number;
  minutes: number;
  seconds: number;
  getTime = () => {
    const currentDateTime = new Date();
    this.years = currentDateTime.getFullYear();
    this.months = currentDateTime.getMonth() + 1;
    this.days = currentDateTime.getDate();
    this.hours = currentDateTime.getHours();
    this.minutes = currentDateTime.getMinutes();
    this.seconds = currentDateTime.getSeconds();
  };

  ngOnInit() {
    this.interval = setInterval(() => {
      this.getTime();
    }, 1000);
  }

  ngOnDestroy() {
    clearInterval(this.interval);
  }
}

<span>
  {{years}}-{{months < 10 ? "0" + months : months}}-{{days < 10 ? "0" + days : days}}{{" "}}
  {{hours < 10 ? " 0" + hours : hours}}:{{minutes < 10 ? "0" + minutes : minutes}}: {{seconds < 10 ? "0" + seconds :
    seconds}} </span>

// src/UIs/bff/reactjs/src/components/Timer/Timer.tsx
import { useState, useEffect } from "react";

const Timer = () => {
  const [years, setYears] = useState(0);
  const [months, setMonths] = useState(0);
  const [days, setDays] = useState(0);
  const [hours, setHours] = useState(0);
  const [minutes, setMinutes] = useState(0);
  const [seconds, setSeconds] = useState(0);

  const getTime = () => {
    const currentDateTime = new Date();
    setYears(currentDateTime.getFullYear());
    setMonths(currentDateTime.getMonth() + 1);
    setDays(currentDateTime.getDate());
    setHours(currentDateTime.getHours());
    setMinutes(currentDateTime.getMinutes());
    setSeconds(currentDateTime.getSeconds());
  };

  useEffect(() => {
    const interval = setInterval(() => getTime(), 1000);
    return () => clearInterval(interval);
  }, []);

  return (
    <>
      <span>
        {years}-{months < 10 ? "0" + months : months}-{days < 10 ? "0" + days : days}{" "}
        {hours < 10 ? "0" + hours : hours}:{minutes < 10 ? "0" + minutes : minutes}:
        {seconds < 10 ? "0" + seconds : seconds}
      </span>
    </>
  );
};

export default Timer;
