// src/UIs/vuejs/src/components/Timer.vue
<template>
  <span>
    {{ years }}-{{ months < 10 ? "0" + months : months }}-{{ days < 10 ? "0" + days : days }}{{ " " }} {{ hours < 10
        ? " 0" + hours : hours
    }}:{{ minutes < 10 ? "0" + minutes : minutes }}: {{ seconds < 10 ? "0" + seconds : seconds
}} </span>
</template>
<script lang="ts">
export default {
  data() {
    return {
      interval: 0 as number,
      years: 0,
      months: 0,
      days: 0,
      hours: 0,
      minutes: 0,
      seconds: 0
    };
  },
  computed: {
  },
  methods: {
    getTime() {
      const currentDateTime = new Date();
      this.years = currentDateTime.getFullYear();
      this.months = currentDateTime.getMonth() + 1;
      this.days = currentDateTime.getDate();
      this.hours = currentDateTime.getHours();
      this.minutes = currentDateTime.getMinutes();
      this.seconds = currentDateTime.getSeconds();
    }
  },
  created() {
    this.interval = setInterval(() => {
      this.getTime();
    }, 1000);
  },
  destroyed() {
    clearInterval(this.interval);
  }
};
</script>
<style scoped>

</style>

// src/UIs/bff/reactjs/src/components/Timer/Timer.tsx
import { useState, useEffect } from "react";

const Timer = () => {
  const [years, setYears] = useState(0);
  const [months, setMonths] = useState(0);
  const [days, setDays] = useState(0);
  const [hours, setHours] = useState(0);
  const [minutes, setMinutes] = useState(0);
  const [seconds, setSeconds] = useState(0);

  const getTime = () => {
    const currentDateTime = new Date();
    setYears(currentDateTime.getFullYear());
    setMonths(currentDateTime.getMonth() + 1);
    setDays(currentDateTime.getDate());
    setHours(currentDateTime.getHours());
    setMinutes(currentDateTime.getMinutes());
    setSeconds(currentDateTime.getSeconds());
  };

  useEffect(() => {
    const interval = setInterval(() => getTime(), 1000);
    return () => clearInterval(interval);
  }, []);

  return (
    <>
      <span>
        {years}-{months < 10 ? "0" + months : months}-{days < 10 ? "0" + days : days}{" "}
        {hours < 10 ? "0" + hours : hours}:{minutes < 10 ? "0" + minutes : minutes}:
        {seconds < 10 ? "0" + seconds : seconds}
      </span>
    </>
  );
};

export default Timer;
