// src/UIs/angular/src/app/files/upload-file/upload-file.component.ts
import { Component, OnInit } from "@angular/core";
import { IFile } from "../file";
import { Router, ActivatedRoute } from "@angular/router";
import { FileService } from "../file.service";
import { NgModel, NgForm } from "@angular/forms";

@Component({
  selector: "app-upload-file",
  templateUrl: "./upload-file.component.html",
  styleUrls: ["./upload-file.component.css"],
})
export class UploadFileComponent implements OnInit {
  file: IFile = {
    id: "00000000-0000-0000-0000-000000000000",
    name: null,
    description: null,
    uploadedTime: null,
    fileName: null,
    size: 0,
    formFile: null,
    encrypted: false,
  };
  postErrorMessage: string = "";
  postError = false;
  isDirty = false;

  constructor(
    private fileService: FileService,
    private router: Router,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {}

  onBlur(field: NgModel) {
    if (field.dirty) {
      this.isDirty = true;
    }
    console.log("in onBlur: ", field.valid);
  }

  handleFileInput(files: FileList) {
    this.file.formFile = files.item(0);
  }

  onSubmit(form: NgForm) {
    console.log("in onSubmit: ", form.value, this.file);
    if (form.valid && this.file.formFile) {
      this.fileService.uploadFile(this.file).subscribe(
        (result) => {
          console.log("success: ", result);
          this.isDirty = false;
          this.router.navigate(["/files/edit", result.id]);
        },
        (error) => this.onHttpError(error)
      );
    } else {
      this.postError = true;
      this.postErrorMessage = "Please fix the errors";
    }
  }

  onHttpError(errorResponse: any) {
    console.log("error: ", errorResponse);
    this.postError = true;
    this.postErrorMessage = errorResponse.error.errorMessage;
  }
}

<div class="card">
  <div class="card-header">Upload File</div>
  <div class="card-body">
    <div class="row" [hidden]="!postError" class="alert alert-danger">
      {{ postErrorMessage }}
    </div>
    <form #form="ngForm" (ngSubmit)="onSubmit(form)">
      <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
          <input
            id="name"
            name="name"
            class="form-control"
            [(ngModel)]="file.name"
            required
            #nameField="ngModel"
            (blur)="onBlur(nameField)"
            [class.is-invalid]="form.submitted && nameField.invalid"
          />
          <span class="invalid-feedback"> Enter a name </span>
        </div>
      </div>
      <div class="form-group row">
        <label for="description" class="col-sm-2 col-form-label"
          >Description</label
        >
        <div class="col-sm-10">
          <input
            id="description"
            name="description"
            class="form-control"
            [(ngModel)]="file.description"
            required
            #descriptionField="ngModel"
            (blur)="onBlur(descriptionField)"
            [class.is-invalid]="form.submitted && descriptionField.invalid"
          />
          <span class="invalid-feedback"> Enter a description </span>
        </div>
      </div>
      <div class="form-group row">
        <label for="formFile" class="col-sm-2 col-form-label">File</label>
        <div class="col-sm-10">
          <input
            id="formFile"
            type="file"
            name="formFile"
            class="form-control"
            required
            (change)="handleFileInput($event.target.files)"
            [class.is-invalid]="form.submitted && !file.formFile"
          />
          <span class="invalid-feedback"> Select a file </span>
        </div>
      </div>
      <div class="form-group row">
        <label for="encrypted" class="col-sm-2 col-form-label">Encrypted</label>
        <div class="col-sm-10">
          <input
            type="checkbox"
            id="encrypted"
            name="encrypted"
            [(ngModel)]="file.encrypted"
          />
        </div>
      </div>
      <div class="form-group row">
        <label for="description" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
          <button class="btn btn-primary">Save</button>
        </div>
      </div>
    </form>
  </div>
  <div class="card-footer">
    <a
      class="btn btn-outline-secondary"
      [routerLink]="['/files']"
      style="width: 80px"
    >
      <i class="fa fa-chevron-left"></i> Back
    </a>
  </div>
</div>

// src/UIs/bff/reactjs/src/containers/Files/UploadFile/UploadFile.tsx
import { useState } from "react";
import { NavLink, Navigate } from "react-router-dom";
import { checkValidity } from "../../../shared/utility";
import axios from "../axios";

const UploadFile = () => {
  const [state, setState] = useState({
    title: "Upload File",
    controls: {
      name: {
        validation: {
          required: true,
          minLength: 3,
        },
        error: {
          required: false,
          minLength: false,
        },
        valid: false,
        touched: false,
      },
      description: {
        validation: {
          required: true,
          maxLength: 100,
        },
        error: {
          required: false,
          maxLength: false,
        },
        valid: false,
        touched: false,
      },
    },
    valid: false,
    formFile: null,
    hasFile: false,
    submitted: false,
    errorMessage: null,
    saved: false,
  });

  const [file, setFile] = useState({
    name: "",
    description: "",
    fileName: "",
    encrypted: false,
  });

  const fieldChanged = (event) => {
    let value = event.target.value;

    if (event.target.type == "checkbox") {
      value = event.target.checked;
    }

    checkFieldValidity(event.target.name, value);

    setFile({
      ...file,
      [event.target.name]: value,
    });
  };

  const checkFieldValidity = (name, value) => {
    const control = state.controls[name];
    if (!control) return true;

    const rules = control.validation;
    const validationRs = checkValidity(value, rules);

    setState((preState) => {
      return {
        ...preState,
        controls: {
          ...preState.controls,
          [name]: {
            ...preState.controls[name],
            error: validationRs,
            valid: validationRs.isValid,
          },
        },
      };
    });

    return validationRs.isValid;
  };

  const handleFileInput = (event) => {
    var formFile = event.target.files.item(0);
    setState({ ...state, formFile: formFile, hasFile: !!formFile });
    setFile({
      ...file,
      [event.target.name]: formFile,
    });
  };

  const onSubmit = async (event) => {
    event.preventDefault();
    setState({ ...state, submitted: true });
    let isValid = true;
    for (let fieldName in state.controls) {
      isValid = checkFieldValidity(fieldName, file[fieldName]) && isValid;
    }

    if (isValid && state.hasFile) {
      try {
        const formData = new FormData();
        formData.append("formFile", file.formFile);
        formData.append("name", file.name);
        formData.append("description", file.description);
        formData.append("encrypted", file.encrypted.toString());
        const response = await axios.post("", formData);
        setFile(response.data);
        setState({ ...state, saved: true });
      } catch (error) {
        console.log(error);
      }
    }
  };

  const form = (
    <div className="card">
      <div className="card-header">{state.title}</div>
      <div className="card-body">
        {state.errorMessage ? (
          <div className="row alert alert-danger">{state.errorMessage}</div>
        ) : null}
        <form onSubmit={onSubmit}>
          <div className="mb-3 row">
            <label htmlFor="name" className="col-sm-2 col-form-label">
              Name
            </label>
            <div className="col-sm-10">
              <input
                id="name"
                name="name"
                className={
                  "form-control " +
                  (state.submitted && !state.controls["name"].valid ? "is-invalid" : "")
                }
                value={file?.name}
                onChange={(event) => fieldChanged(event)}
              />
              <span className="invalid-feedback">
                {state.controls["name"].error.required ? <span>Enter a name</span> : null}
                {state.controls["name"].error.minLength ? (
                  <span>The name must be longer than 3 characters.</span>
                ) : null}
              </span>
            </div>
          </div>
          <div className="mb-3 row">
            <label htmlFor="description" className="col-sm-2 col-form-label">
              Description
            </label>
            <div className="col-sm-10">
              <input
                id="description"
                name="description"
                className={
                  "form-control " +
                  (state.submitted && !state.controls["description"].valid ? "is-invalid" : "")
                }
                value={file?.description}
                onChange={(event) => fieldChanged(event)}
              />
              <span className="invalid-feedback">
                {state.controls["description"].error.required ? (
                  <span>Enter a description</span>
                ) : null}
                {state.controls["description"].error.maxLength ? (
                  <span>The code must be less than 100 characters.</span>
                ) : null}
              </span>
            </div>
          </div>
          <div className="mb-3 row">
            <label htmlFor="formFile" className="col-sm-2 col-form-label">
              File
            </label>
            <div className="col-sm-10">
              <input
                id="formFile"
                type="file"
                name="formFile"
                className={
                  "form-control " + (state.submitted && !state.hasFile ? "is-invalid" : "")
                }
                onChange={handleFileInput}
              />
              <span className="invalid-feedback">Select a file</span>
            </div>
          </div>
          <div className="mb-3 row">
            <label htmlFor="encrypted" className="col-sm-2 col-form-label">
              Encrypted
            </label>
            <div className="col-sm-10">
              <input
                type="checkbox"
                id="encrypted"
                name="encrypted"
                checked={file?.encrypted}
                onChange={(event) => fieldChanged(event)}
              />
            </div>
          </div>
          <div className="mb-3 row">
            <label htmlFor="description" className="col-sm-2 col-form-label"></label>
            <div className="col-sm-10">
              <button className="btn btn-primary">Save</button>
            </div>
          </div>
        </form>
      </div>
      <div className="card-footer">
        <NavLink className="btn btn-outline-secondary" to="/files" style={{ width: "80px" }}>
          <i className="fa fa-chevron-left"></i> Back
        </NavLink>
      </div>
    </div>
  );

  return state.submitted && state.saved ? <Navigate to={"/files/edit/" + file.id} /> : form;
};

export default UploadFile;
