// src/UIs/bff/reactjs/src/components/Notification/Notification.tsx
import { useEffect } from "react";
import { HubConnectionBuilder } from "@microsoft/signalr";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import env from "../..//environments";

function Notification() {
  useEffect(() => {
    const connection = new HubConnectionBuilder()
      .withUrl(env.ResourceServer.NotificationEndpoint, {})
      .withAutomaticReconnect()
      .build();

    connection.start().then(
      function () {
        console.log("Connected to NotificationHub");
        toast.success("Connected to NotificationHub");
      },
      function () {
        console.log(
          "Cannot connect to NotificationHub: " + env.ResourceServer.NotificationEndpoint
        );
        toast.error(
          "Cannot connect to NotificationHub: " + env.ResourceServer.NotificationEndpoint
        );
      }
    );

    connection.on("ReceiveMessage", (message) => {
      console.log("Received Message from NotificationHub: " + message);
      toast.info("Received Message from NotificationHub: " + message);
    });
  }, []);

  return <ToastContainer />;
}

export default Notification;

// src/UIs/vuejs/src/components/Notification.vue
<script>
import { HubConnectionBuilder } from '@microsoft/signalr'
import { useToast } from 'vue-toastification'

import authService from '../auth/authService'
import env from '../../environments'

export default {
  setup() {
    const toast = useToast()
    return { toast }
  },
  mounted() {
    const connection = new HubConnectionBuilder()
      .withUrl(env.ResourceServer.NotificationEndpoint, {
        accessTokenFactory: () => authService.getAccessToken(),
      })
      .withAutomaticReconnect()
      .build()

    let vm = this

    connection.start().then(
      function () {
        // console.log("Connected to NotificationHub");
        vm.toast.success('Connected to NotificationHub', {
          timeout: 2000,
        })
      },
      function () {
        // console.log(
        //   "Cannot connect to NotificationHub: " +
        //     env.ResourceServer.NotificationEndpoint
        // );
        vm.toast.error(
          'Cannot connect to NotificationHub: ' + env.ResourceServer.NotificationEndpoint,
        )
      },
    )

    connection.on('ReceiveMessage', (message) => {
      // console.log("Received Message from NotificationHub: " + message);
      vm.toast.info('Received Message from NotificationHub: ' + message)
    })
  },
}
</script>
