// src/UIs/reactjs/src/components/Star/Star.tsx
import { StarIcon } from "lucide-react";

import classes from "./Star.module.css";

const Star = props => {
  const width = (props.rating * 75) / 5;
  return (
    <div
      className={classes.Star}
      style={{ width: width }}
      title="rating"
      onClick={() =>
        props.ratingClicked
          ? props.ratingClicked(`The rating ${props.rating} was clicked!`)
          : null
      }
    >
      <div style={{ width: "75px" }}>
        {Array.from({ length: 5 }, (_, index) => (
          <StarIcon key={index} size={15} fill="currentColor" aria-hidden="true" />
        ))}
      </div>
    </div>
  );
};

export default Star;

// src/UIs/vuejs/src/components/Star.vue
<template>
  <div class="crop" :style="{width: starWidth + 'px'}" :title="`${rating}`" @click="onClick">
    <div style="width: 75px">
      <Star v-for="index in 5" :key="index" :size="15" fill="currentColor" aria-hidden="true" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { Star } from 'lucide-vue-next'

interface Props {
  rating: number
}

const props = defineProps<Props>()
const emit = defineEmits<{
  ratingClicked: [message: string]
}>()

const starWidth = computed(() => {
  return (props.rating * 75) / 5
})

const onClick = () => {
  emit('ratingClicked', `The rating ${props.rating} was clicked!`)
}
</script>

<style scoped>
.crop {
  overflow: hidden;
}
div {
  cursor: pointer;
}
</style>
