// src/UIs/nextjs/src/containers/Home/Home.tsx
import React from "react";
import ActionIcon from "../../components/ActionIcon/ActionIcon";
import Image from "next/image";
import Timer from "../../components/Timer/Timer";

import "./Home.css";

function Home() {
  const date = new Date();

  const nextVersion = "16.0.6";

  return (
    <div className="card">
      <div className="card-header">
        <ActionIcon action="home" />
        Welcome ClassifiedAds NextJs version: {nextVersion}
        <div style={{ float: "right", color: "green" }}>
          <Timer />
        </div>
      </div>
      <div className="card-body">
        <div className="container-fluid">
          <div className="text-center">
            <Image
              src="next.svg"
              alt="logo"
              className="img-responsive center-block"
              width={200}
              height={200}
              style={{ maxHeight: "300px", paddingBottom: "10px" }}
            />
          </div>

          <div className="text-center">Developed by:</div>
          <div className="text-center">
            <h3>Phong Nguyen</h3>
          </div>

          <div className="text-center">@phongnguyend</div>
          <div className="text-center">
            <a href="https://github.com/phongnguyend/Practical.CleanArchitecture">
              <ActionIcon action="external" /> Practical.CleanArchitecture
            </a>
          </div>
          <div className="text-center">
            <strong>NextJs v{nextVersion}</strong>
          </div>
          <div className="text-center">{date.toLocaleDateString()}</div>
        </div>
      </div>
    </div>
  );
}

export default Home;

// src/UIs/vuejs/src/views/Home.vue
<template>
  <div class="card">
    <div class="card-header"><ActionIcon action="home" />{{ appendVersion(pageTitle) }}
      <div style="float: right;color: green">
        <app-timer></app-timer>
      </div>
    </div>
    <div class="card-body">
      <div class="container-fluid">
        <div class="text-center">
          <img src="../assets/logo.png" class="img-responsive center-block"
            style="max-height:300px;padding-bottom:10px" />
        </div>

        <div class="text-center">Developed by:</div>
        <div class="text-center">
          <h3>Phong Nguyen</h3>
        </div>
        <div class="text-center">@phongnguyend</div>
        <div class="text-center">
          <a href="https://github.com/phongnguyend/Practical.CleanArchitecture"><ActionIcon action="external" />Practical.CleanArchitecture</a>
        </div>
        <div class="text-center">
          <strong>vuejs v{{ version }}</strong>
        </div>
        <div class="text-center">{{ appendCurrentDateTime("") }}</div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, version } from 'vue'
import AppTimer from '../components/Timer.vue'

const pageTitle = ref('Welcome ClassifiedAds Vue')

const appendVersion = (value: string) => {
  return value + ' ' + version
}

const appendCurrentDateTime = (value: string) => {
  return value + ' ' + new Date()
}
</script>
