// src/UIs/reactjs/src/components/Nav/Nav.tsx
import React from "react";
import { NavLink } from "react-router-dom";

import { isAuthenticated } from "../../containers/Auth/authService";
import classes from "./Nav.module.css";

const Nav = () => {
  const pageTitle = "ClassifiedAds.React";
  return (
    <nav className={"navbar navbar-expand navbar-light bg-light " + classes.Nav}>
      <a className="navbar-brand" href="/">
        {pageTitle + " " + React.version}
      </a>
      <ul className="nav nav-pills">
        <li>
          <NavLink className="nav-link" to="/home">
            Home
          </NavLink>
        </li>
        <li>
          <NavLink className="nav-link" to="/settings">
            Settings
          </NavLink>
        </li>
        <li>
          <NavLink className="nav-link" to="/files">
            Files
          </NavLink>
        </li>
        <li>
          <NavLink className="nav-link" to="/products">
            Products
          </NavLink>
        </li>
        <li>
          <NavLink className="nav-link" to="/users">
            Users
          </NavLink>
        </li>
        <li>
          <NavLink className="nav-link" to="/auditlogs">
            Audit Logs
          </NavLink>
        </li>

        {!isAuthenticated() ? (
          <li>
            <NavLink className="nav-link" to="/login">
              Login
            </NavLink>
          </li>
        ) : null}

        {isAuthenticated() ? (
          <li>
            <NavLink className="nav-link" to="/logout">
              Logout
            </NavLink>
          </li>
        ) : null}
      </ul>
    </nav>
  );
};

export default Nav;

// src/UIs/vuejs/src/views/Nav.vue
<template>
  <nav class="navbar navbar-expand navbar-light bg-light">
    <a class="navbar-brand" href="/">{{ pageTitle | appendVersion }}</a>
    <ul class="nav nav-pills">
      <li>
        <router-link class="nav-link" to="/" active-class="active" exact
          >Home</router-link
        >
      </li>
      <li>
        <router-link class="nav-link" to="/settings" active-class="active"
          >Settings</router-link
        >
      </li>
      <li>
        <router-link class="nav-link" to="/files" active-class="active"
          >Files</router-link
        >
      </li>
      <li>
        <router-link class="nav-link" to="/products" active-class="active"
          >Products</router-link
        >
      </li>
      <li>
        <router-link class="nav-link" to="/users" active-class="active"
          >Users</router-link
        >
      </li>
      <li>
        <router-link class="nav-link" to="/auditlogs" active-class="active"
          >Audit Logs</router-link
        >
      </li>
      <li v-if="!isAuthenticated">
        <a class="nav-link" @click="login" href="javascript:void(0)">Login</a>
      </li>
      <li v-if="isAuthenticated">
        <a class="nav-link" @click="logout" href="javascript:void(0)">Logout</a>
      </li>
    </ul>
  </nav>
</template>

<script lang="ts">
import Vue from "vue";
export default Vue.extend({
  data() {
    return { pageTitle: "ClassifiedAds.Vue" };
  },
  computed: {
    isAuthenticated(): boolean {
      return this.$store.state.authService.isAuthenticated();
    }
  },
  methods: {
    login() {
      this.$store.state.authService.login("");
    },
    logout() {
      this.$store.state.authService.logout();
    }
  }
});
</script>

<style scoped>
.nav-link {
  font-size: large;
}
</style>
