// src/UIs/bff/reactjs/src/components/Nav/Nav.tsx
import React from "react";
import { NavLink } from "react-router-dom";

import { isAuthenticated, logout } from "../../containers/Auth/authService";
import classes from "./Nav.module.css";

const Nav = () => {
  const pageTitle = "ClassifiedAds.React";
  return (
    <nav
      className={"navbar navbar-expand navbar-light bg-light " + classes.Nav}
      style={{ paddingLeft: "1rem", paddingRight: "1rem" }}
    >
      <a className="navbar-brand" href="/">
        {pageTitle + " " + React.version}
      </a>
      <ul className="nav nav-pills">
        <li>
          <NavLink className="nav-link" to="/home">
            Home
          </NavLink>
        </li>
        <li>
          <NavLink className="nav-link" to="/settings">
            Settings
          </NavLink>
        </li>
        <li>
          <NavLink className="nav-link" to="/files">
            Files
          </NavLink>
        </li>
        <li>
          <NavLink className="nav-link" to="/products">
            Products
          </NavLink>
        </li>
        <li>
          <NavLink className="nav-link" to="/users">
            Users
          </NavLink>
        </li>
        <li>
          <NavLink className="nav-link" to="/auditlogs">
            Audit Logs
          </NavLink>
        </li>

        {!isAuthenticated() ? (
          <li>
            <a className="nav-link" href="/login">
              Login
            </a>
          </li>
        ) : null}

        {isAuthenticated() ? (
          <li>
            <a className="nav-link" onClick={logout} href="/logout">
              Logout
            </a>
          </li>
        ) : null}
      </ul>
    </nav>
  );
};

export default Nav;

// src/UIs/vuejs/src/views/Nav.vue
<template>
  <nav
    class="navbar navbar-expand navbar-light bg-light"
    :style="{ paddingLeft: '1rem', paddingRight: '1rem' }"
  >
    <a class="navbar-brand" href="/">{{ appendVersion(pageTitle) }}</a>
    <ul class="nav nav-pills">
      <li>
        <router-link class="nav-link" to="/" active-class="active" exact>Home</router-link>
      </li>
      <li>
        <router-link class="nav-link" to="/settings" active-class="active">Settings</router-link>
      </li>
      <li>
        <router-link class="nav-link" to="/files" active-class="active">Files</router-link>
      </li>
      <li>
        <router-link class="nav-link" to="/products" active-class="active">Products</router-link>
      </li>
      <li>
        <router-link class="nav-link" to="/users" active-class="active">Users</router-link>
      </li>
      <li>
        <router-link class="nav-link" to="/auditlogs" active-class="active">Audit Logs</router-link>
      </li>
      <li v-if="!isAuthenticated">
        <a class="nav-link" @click="login" href="javascript:void(0)">Login</a>
      </li>
      <li v-if="isAuthenticated">
        <a class="nav-link" @click="logout" href="javascript:void(0)">Logout</a>
      </li>
    </ul>
  </nav>
</template>

<script lang="ts">
import { defineComponent, version } from 'vue'
import { useStore } from 'vuex'

export default defineComponent({
  setup() {
    return { store: useStore() }
  },
  data() {
    return { pageTitle: 'ClassifiedAds.Vue' }
  },
  computed: {
    isAuthenticated(): boolean {
      return this.store.state.authService.isAuthenticated()
    },
  },
  methods: {
    login() {
      this.store.state.authService.login('')
    },
    logout() {
      this.store.state.authService.logout()
    },
    appendVersion(value: string) {
      return value + ' ' + version
    },
  },
})
</script>

<style scoped>
.nav-link {
  font-size: large;
}
</style>
