// src/ClassifiedAds.UIs/vuejs/src/views/Nav.vue
<template>
  <nav class="navbar navbar-expand navbar-light bg-light">
    <a class="navbar-brand" href="/">{{ pageTitle | appendVersion }}</a>
    <ul class="nav nav-pills">
      <li>
        <router-link class="nav-link" to="/" active-class="active" exact>Home</router-link>
      </li>
      <li>
        <router-link class="nav-link" to="/files" active-class="active">File</router-link>
      </li>
      <li>
        <router-link class="nav-link" to="/products" active-class="active">Product</router-link>
      </li>
      <li>
        <router-link class="nav-link" to="/auditlogs" active-class="active">Audit Logs</router-link>
      </li>
      <li v-if="!isAuthenticated">
        <a class="nav-link" @click="login" href="javascript:void(0)">Login</a>
      </li>
      <li v-if="isAuthenticated">
        <a class="nav-link" @click="logout" href="javascript:void(0)">Logout</a>
      </li>
    </ul>
  </nav>
</template>

<script>
export default {
  data() {
    return { pageTitle: "ClassifiedAds.Vue" };
  },
  computed: {
    isAuthenticated() {
      return this.$store.state.authService.isAuthenticated();
    },
  },
  methods: {
    login() {
      this.$store.state.authService.login("");
    },
    logout() {
      this.$store.state.authService.logout();
    },
  },
};
</script>

<style scoped>
.nav-link {
  font-size: large;
}
</style>

// src/ClassifiedAds.UIs/reactjs/src/components/Nav/Nav.js
import React, { Component } from "react";
import { NavLink } from "react-router-dom";
import { connect } from "react-redux";

import classes from "./Nav.module.css";

class Nav extends Component {
  render() {
    const pageTitle = "ClassifiedAds.React";
    return (
      <nav
        className={"navbar navbar-expand navbar-light bg-light " + classes.Nav}
      >
        <a className="navbar-brand" href="/">
          {pageTitle + " " + React.version}
        </a>
        <ul className="nav nav-pills">
          <li>
            <NavLink className="nav-link" to="/home">
              Home
            </NavLink>
          </li>
          <li>
            <NavLink className="nav-link" to="/files">
              File
            </NavLink>
          </li>
          <li>
            <NavLink className="nav-link" to="/products">
              Product
            </NavLink>
          </li>

          <li>
            <NavLink className="nav-link" to="/auditlogs">
              Audit Logs
            </NavLink>
          </li>

          {!this.props.authService.isAuthenticated() ? (
            <li>
              <NavLink
                className="nav-link"
                to="/login"
                onClick={this.props.authService.login}
                href="javascript:void(0)"
              >
                Login
              </NavLink>
            </li>
          ) : null}

          {this.props.authService.isAuthenticated() ? (
            <li>
              <NavLink
                className="nav-link"
                to="/logout"
                onClick={this.props.authService.logout}
                href="javascript:void(0)"
              >
                Logout
              </NavLink>
            </li>
          ) : null}
        </ul>
      </nav>
    );
  }
}
const mapStateToProps = (state) => {
  return {
    user: state.auth.user,
    authService: state.auth.authService,
  };
};

const mapDispatchToProps = (dispatch) => {
  return {};
};

export default connect(mapStateToProps, mapDispatchToProps)(Nav);
