// src/UIs/reactjs/src/containers/Auth/OidcLoginRedirect.tsx
import { UserManager, User, WebStorageStateStore, UserManagerSettings } from "oidc-client-ts";
import { Component } from "react";

import env from "../../environments";

var config = {
  authority: env.OpenIdConnect.Authority,
  client_id: env.OpenIdConnect.ClientId,
  userStore: new WebStorageStateStore({ store: window.localStorage }),
  response_mode: "query",
} as UserManagerSettings;

var mgr = new UserManager(config);

class OidcLoginRedirect extends Component {
  componentDidMount() {
    mgr.signinRedirectCallback().then(
      (user: User) => {
        window.history.replaceState({}, window.document.title, window.location.origin);

        let returnUrl = localStorage.getItem("returnUrl");
        if (returnUrl) {
          localStorage.removeItem("returnUrl");
        } else {
          returnUrl = "/";
        }
        window.location.href = returnUrl;
      },
      (error) => {
        console.error(error);
      }
    );
  }

  render() {
    return <div>Loading ...</div>;
  }
}

export default OidcLoginRedirect;

// src/UIs/vuejs/src/auth/OidcLoginRedirect.vue
<template>
  <div>Loading ...</div>
</template>

<script>
import { UserManager, User, WebStorageStateStore } from "oidc-client-ts";

import env from "../../environments";

var config = {
  authority: env.OpenIdConnect.Authority,
  client_id: env.OpenIdConnect.ClientId,
  userStore: new WebStorageStateStore({ store: window.localStorage }),
  response_mode: "query"
};
var mgr = new UserManager(config);
export default {
  created() {
    mgr.signinRedirectCallback().then(
      () => {
        window.history.replaceState(
          {},
          window.document.title,
          window.location.origin
        );

        const returnUrl = localStorage.getItem("returnUrl");
        if (returnUrl) {
          localStorage.removeItem("returnUrl");
          window.location = returnUrl;
        } else {
          window.location = "/";
        }
      },
      error => {
        //console.error(error);
      }
    );
  }
};
</script>
