// src/UIs/angular/src/app/shared/theme-switcher.component.ts
import { Component, ElementRef, OnDestroy, OnInit, ViewChild } from "@angular/core";
import { NgIcon } from "@ng-icons/core";

type Theme = "system" | "light" | "dark";
const storageKey = "classifiedads-theme";

@Component({
  selector: "app-theme-switcher",
  standalone: true,
  imports: [NgIcon],
  template: `
    <details #menu class="theme-switcher">
      <summary class="theme-switcher-trigger" [title]="'Theme: ' + theme" [attr.aria-label]="'Theme: ' + theme + '. Choose appearance'">
        <ng-icon [name]="currentIcon" size="20" aria-hidden="true" />
      </summary>
      <div class="theme-switcher-menu" role="group" aria-label="Appearance">
        <button type="button" class="theme-switcher-option" [attr.aria-pressed]="theme === 'system'" (click)="choose('system')">
          <ng-icon name="lucideMonitor" size="17" aria-hidden="true" /><span>System</span>
          @if (theme === 'system') { <ng-icon name="lucideCheck" size="16" class="theme-switcher-check" aria-hidden="true" /> }
        </button>
        <button type="button" class="theme-switcher-option" [attr.aria-pressed]="theme === 'light'" (click)="choose('light')">
          <ng-icon name="lucideSun" size="17" aria-hidden="true" /><span>Light</span>
          @if (theme === 'light') { <ng-icon name="lucideCheck" size="16" class="theme-switcher-check" aria-hidden="true" /> }
        </button>
        <button type="button" class="theme-switcher-option" [attr.aria-pressed]="theme === 'dark'" (click)="choose('dark')">
          <ng-icon name="lucideMoon" size="17" aria-hidden="true" /><span>Dark</span>
          @if (theme === 'dark') { <ng-icon name="lucideCheck" size="16" class="theme-switcher-check" aria-hidden="true" /> }
        </button>
      </div>
    </details>
  `,
  styleUrls: ["./theme-switcher.component.css"],
})
export class ThemeSwitcherComponent implements OnInit, OnDestroy {
  @ViewChild("menu") menu?: ElementRef<HTMLDetailsElement>;
  theme: Theme = "system";
  private media = window.matchMedia("(prefers-color-scheme: dark)");

  get currentIcon(): "lucideMonitor" | "lucideSun" | "lucideMoon" {
    return this.theme === "light" ? "lucideSun" : this.theme === "dark" ? "lucideMoon" : "lucideMonitor";
  }

  private readTheme(): Theme {
    try {
      const stored = localStorage.getItem(storageKey);
      return stored === "light" || stored === "dark" ? stored : "system";
    } catch {
      return "system";
    }
  }

  private applyTheme(theme: Theme) {
    const dark = theme === "dark" || (theme === "system" && this.media.matches);
    document.documentElement.setAttribute("data-bs-theme", dark ? "dark" : "light");
  }

  private onSystemChange = () => {
    if (this.readTheme() === "system") this.applyTheme("system");
  };

  private onOutside = (event: PointerEvent) => {
    if (this.menu && !this.menu.nativeElement.contains(event.target as Node)) this.menu.nativeElement.removeAttribute("open");
  };

  private onStorage = (event: StorageEvent) => {
    if (event.key === storageKey) {
      this.theme = this.readTheme();
      this.applyTheme(this.theme);
    }
  };

  ngOnInit() {
    this.theme = this.readTheme();
    this.applyTheme(this.theme);
    this.media.addEventListener("change", this.onSystemChange);
    document.addEventListener("pointerdown", this.onOutside);
    window.addEventListener("storage", this.onStorage);
  }

  ngOnDestroy() {
    this.media.removeEventListener("change", this.onSystemChange);
    document.removeEventListener("pointerdown", this.onOutside);
    window.removeEventListener("storage", this.onStorage);
  }

  choose(theme: Theme) {
    try { localStorage.setItem(storageKey, theme); } catch { /* Apply for this page. */ }
    this.theme = theme;
    this.applyTheme(theme);
    this.menu?.nativeElement.removeAttribute("open");
  }
}

// src/UIs/nextjs/src/components/ThemeSwitcher/ThemeSwitcher.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import { Check, Monitor, Moon, Sun } from "lucide-react";
import "./ThemeSwitcher.css";

type Theme = "system" | "light" | "dark";
const storageKey = "classifiedads-theme";
const choices = [
  { value: "system", label: "System", Icon: Monitor },
  { value: "light", label: "Light", Icon: Sun },
  { value: "dark", label: "Dark", Icon: Moon },
] as const;

const readTheme = (): Theme => {
  try {
    const stored = localStorage.getItem(storageKey);
    return stored === "light" || stored === "dark" ? stored : "system";
  } catch {
    return "system";
  }
};

const applyTheme = (theme: Theme) => {
  const dark = theme === "dark" || (theme === "system" && window.matchMedia("(prefers-color-scheme: dark)").matches);
  document.documentElement.setAttribute("data-bs-theme", dark ? "dark" : "light");
};

const ThemeSwitcher = () => {
  const [theme, setTheme] = useState<Theme>("system");
  const menu = useRef<HTMLDetailsElement>(null);

  useEffect(() => {
    const saved = readTheme();
    setTheme(saved);
    applyTheme(saved);
    const media = window.matchMedia("(prefers-color-scheme: dark)");
    const onSystemChange = () => { if (readTheme() === "system") applyTheme("system"); };
    const onStorage = (event: StorageEvent) => {
      if (event.key === storageKey) {
        const updated = readTheme();
        setTheme(updated);
        applyTheme(updated);
      }
    };
    const onOutside = (event: PointerEvent) => {
      if (menu.current && !menu.current.contains(event.target as Node)) menu.current.removeAttribute("open");
    };
    document.addEventListener("pointerdown", onOutside);
    media.addEventListener("change", onSystemChange);
    window.addEventListener("storage", onStorage);
    return () => {
      document.removeEventListener("pointerdown", onOutside);
      media.removeEventListener("change", onSystemChange);
      window.removeEventListener("storage", onStorage);
    };
  }, []);

  const choose = (value: Theme) => {
    try { localStorage.setItem(storageKey, value); } catch { /* The choice still applies for this page. */ }
    setTheme(value);
    applyTheme(value);
    menu.current?.removeAttribute("open");
  };

  const CurrentIcon = choices.find((choice) => choice.value === theme)!.Icon;
  return (
    <details className="theme-switcher" ref={menu}>
      <summary className="theme-switcher-trigger" title={`Theme: ${theme}`} aria-label={`Theme: ${theme}. Choose appearance`}>
        <CurrentIcon size={20} aria-hidden="true" />
      </summary>
      <div className="theme-switcher-menu" role="group" aria-label="Appearance">
        {choices.map(({ value, label, Icon }) => (
          <button key={value} type="button" className="theme-switcher-option" aria-pressed={theme === value} onClick={() => choose(value)}>
            <Icon size={17} aria-hidden="true" /> <span>{label}</span>
            {theme === value && <Check size={16} className="theme-switcher-check" aria-hidden="true" />}
          </button>
        ))}
      </div>
    </details>
  );
};

export default ThemeSwitcher;
